#!/usr/bin/env python3
"""Regenerate XREF.md — tag index, backlinks, shared sources — for a lake corpus.

Deterministic, stdlib-only. Part of the evidence-kit lake profile; run after every
pass:  python3 index.py        (rewrite XREF.md)
       python3 index.py --check  (exit 1 if XREF.md is stale; used by the guard)
"""
import os
import re
import sys
from collections import defaultdict

ROOT = os.path.dirname(os.path.abspath(__file__))
FENCE = re.compile(r"\A---[ \t]*\r?\n(.*?)^---[ \t]*\r?$", re.DOTALL | re.MULTILINE)
FM_TAGS = re.compile(r"^tags:\s*\[([^\]]*)\]", re.MULTILINE)
FM_TITLE = re.compile(r"^title:\s*\"?([^\"\n]+?)\"?\s*$", re.MULTILINE)
LINK = re.compile(r"\[[^\]]*\]\(([^)#\s]+?)(?:#[^)]*)?\)")
URL = re.compile(r"https?://[^\s)\]>|\"']+")
SKIP_FILES = {"XREF.md"}
SKIP_DIRS = {"tests", "mirrors"}          # mirrors enter via MANIFEST parsing only


def walk_md():
    out = []
    for dirpath, dirnames, filenames in os.walk(ROOT):
        rel = os.path.relpath(dirpath, ROOT)
        top = rel.split(os.sep)[0]
        dirnames[:] = sorted(d for d in dirnames if not d.startswith(".")
                             and not (rel == "." and d in SKIP_DIRS))
        for name in sorted(filenames):
            if name.endswith(".md") and name not in SKIP_FILES:
                p = os.path.join(rel, name) if rel != "." else name
                out.append(p.replace(os.sep, "/"))
    return out


def manifests():
    out = []
    for dirpath, dirnames, filenames in os.walk(os.path.join(ROOT, "mirrors")):
        dirnames.sort()
        for name in sorted(filenames):
            if name == "MANIFEST.md":
                out.append(os.path.relpath(os.path.join(dirpath, name), ROOT)
                           .replace(os.sep, "/"))
    return out


def domain(path):
    parts = path.split("/")
    if parts[0] == "mirrors" and len(parts) > 2:
        return parts[1]
    return parts[0] if len(parts) > 1 else "(root)"


def subtopic(path):
    parts = path.split("/")
    return "/".join(parts[:2]) if len(parts) > 1 else "(root)"


def build():
    tag_map = defaultdict(list)             # tag -> [path]
    backlinks = defaultdict(list)           # target -> [source]
    url_map = defaultdict(set)              # url -> {subtopic}
    titles = {}
    for path in walk_md():
        with open(os.path.join(ROOT, path), encoding="utf-8") as fh:
            body = fh.read()
        fm = FENCE.match(body)
        fm_text = fm.group(1) if fm else ""
        t = FM_TITLE.search(fm_text)
        titles[path] = t.group(1) if t else path
        m = FM_TAGS.search(fm_text)
        if m:
            for tag in (x.strip() for x in m.group(1).split(",") if x.strip()):
                tag_map[tag].append(path)
        base = os.path.dirname(path)
        for lm in LINK.finditer(body):
            target = lm.group(1)
            if target.startswith(("http://", "https://", "mailto:", "lake:")):
                continue
            resolved = (target.lstrip("/") if target.startswith("/")
                        else os.path.normpath(os.path.join(base, target)))
            backlinks[resolved.replace(os.sep, "/")].append(path)
        for u in URL.findall(body):
            url_map[u.rstrip(".,;")].add(subtopic(path))
    for mpath in manifests():
        with open(os.path.join(ROOT, mpath), encoding="utf-8") as fh:
            for u in URL.findall(fh.read()):
                url_map[u.rstrip(".,;")].add(subtopic(mpath))
    return tag_map, backlinks, url_map, titles


def render():
    tag_map, backlinks, url_map, titles = build()
    L = ["---", "type: Generated Index",
         "title: \"INDEX — tags, backlinks, shared sources (generated)\"",
         "description: \"Generated by index.py; do not edit. Regenerate after every pass.\"",
         "---", "", "# INDEX (generated — do not edit)", "",
         "## Tag index", ""]
    for tag in sorted(tag_map):
        docs = sorted(set(tag_map[tag]))
        doms = sorted({domain(d) for d in docs})
        cross = " **[cross-domain]**" if len(doms) > 1 else ""
        L.append(f"- `{tag}`{cross}: " + " · ".join(f"[{d}]({d})" for d in docs))
    L += ["", "## Backlinks (cross-domain edges first)", ""]
    edges = []
    for target in sorted(backlinks):
        for src in sorted(set(backlinks[target])):
            edges.append((domain(src) != domain(target), src, target))
    for cross, src, target in sorted(edges, key=lambda e: (not e[0], e[1], e[2])):
        mark = " **[cross-domain]**" if cross else ""
        L.append(f"- [{src}]({src}) → [{target}]({target}){mark}")
    L += ["", "## Shared sources (URL in ≥2 subtopics)", ""]
    for u in sorted(url_map):
        subs = sorted(url_map[u])
        if len(subs) > 1:
            L.append(f"- <{u}> — {', '.join(subs)}")
    return "\n".join(L) + "\n"


def main():
    fresh = render()
    idx = os.path.join(ROOT, "XREF.md")
    current = None
    if os.path.exists(idx):
        with open(idx, encoding="utf-8") as fh:
            current = fh.read()
    if "--check" in sys.argv:
        sys.exit(0 if current == fresh else 1)
    with open(idx, "w", encoding="utf-8") as fh:
        fh.write(fresh)
    print("XREF.md regenerated")


if __name__ == "__main__":
    main()
